from Hurricane import Hurricane
from kml_export import kmlexport
import os

path = os.path.expanduser("/Hurricane-Projection-Assessment/OutputKMLFiles")

Calvin = Hurricane("Calvin")
Calvin.dataPointExtraction()
Calvin.distanceInaccuracy()
kmlexport(Calvin.recordedPos, Calvin.projectedPos, Calvin, path + "/Calvin")
Don = Hurricane("Don")
# Don.resetClass()
Don.dataPointExtraction()
Don.distanceInaccuracy()
kmlexport(Don.recordedPos, Don.projectedPos, Don, path + "/Don")
Dora = Hurricane("Dora")
# Dora.resetClass()
Dora.dataPointExtraction()
Dora.distanceInaccuracy()
kmlexport(Dora.recordedPos, Dora.projectedPos, Dora, path + "/Dora")
Franklin = Hurricane("Franklin")
# Franklin.resetClass()
Franklin.dataPointExtraction()
Franklin.distanceInaccuracy()
kmlexport(Franklin.recordedPos, Franklin.projectedPos, Franklin, path + "/Franklin")
Lee = Hurricane("Lee")
# Lee.resetClass()
Lee.dataPointExtraction()
Lee.distanceInaccuracy()
kmlexport(Lee.recordedPos, Lee.projectedPos, Lee, path + "/Lee")
Margot = Hurricane("Margot")
# # Margot.resetClass()
Margot.dataPointExtraction()
Margot.distanceInaccuracy()
kmlexport(Margot.recordedPos, Margot.projectedPos, Margot, path + "/Margot")
